import { useMemo } from 'react';
import { Filter } from 'bad-words';
import { ProfanityOptions, Profanity } from '@2toad/profanity';

export function useContentFilter() {
  const filter = useMemo(() => new Filter(), []);

  const profanity = useMemo(() => {
    const options: ProfanityOptions = {
      wholeWord: false,
      grawlix: '*',
      grawlixChar: '*',
      languages: ['en'],
    };

    const profanityInstance = new Profanity(options);

    // Palavras específicas em português
    profanityInstance.addWords([
      'puta',
      'merda',
      'caralho',
      'buceta',
      'viado',
      'porra',
      'cu',
      'piranha',
      'vagabundo',
      'fdp',
      'vsf',
      'pqp',
      'bosta',
      'desgraça',
      'idiota',
      'imbecil',
      'babaca',
      'lixo',
      'pau',
      'pinto',
      'piroca',
      'pica',
      'arrombado',
      'cuzao',
      'vadia',
      'prostituta',
      'safado',
      'safada',
      'otario',
      'otaria',
      'retardado',
      'retardada',
      'tnc',
      'pnc',
      'cacete',
      'foda',
      'foder',
      'fuder',
      'fudido',
      'fodido',
      'putaria',
      'putinha',
      'putinho',
      'corno',
      'cornudo',
      'cadela',
      'cachorra',
      'xoxota',
      'xereca',
      'pepeca',
      'rola',
      'roludo',
      'rolinha',
      'cabaço',
      'virgem',
      'broxa',
      'impotente',
      'gay',
      'bicha',
      'boiola',
      'sapatao',
      'lesbica',
      'traveco',
      'macaco',
      'gordo',
      'gorda',
      'baleia',
      'tetuda',
      'peituda',
      'bunduda',
      'rabuda',
      'gostosa',
      'gostoso',
      'tesuda',
      'tesudo',
      'punheta',
      'bronha',
      'masturbar',
      'orgasmo',
      'penis',
      'vagina',
      'anus',
      'bunda',
      'peito',
      'seios',
      'mamilo',
      'testículos',
      'saco',
      'bolsa',
      'escroto',
      'verme',
      'escoria',
      'lezado',
      'lesado',
      'mongol',
      'mongolóide',
      'deficiente',
      'aleijado',
      'doente',
      'cancer',
      'aids',
      'dst',
      'estupro',
      'pedofilo',
      'nazista',
      'hitler',
      'racista',
      'preconceito',
      'discriminação',
      'homofobia',
      'transfobia',
      'xenofobia',
      'misoginia',
      'machista',
      'feminazi',
      'comunista',
      'fascista',
      'terrorista',
      'assassino',
      'ladrão',
      'bandido',
      'criminoso',
      'corrupto',
      'politico',
      'presidente',
      'governador',
      'prefeito',
      'vereador',
      'deputado',
      'senador',
      'judeu',
      'preto',
      'negro',
      'branco',
      'indio',
      'cigano',
      'nordestino',
      'baiano',
      'paraiba',
      'favela',
      'favelado',
      'pobre',
      'mendigo',
      'morador de rua',
      'cracudo',
      'maconheiro',
      'drogado',
      'bebado',
      'alcoolatra',
      'viciado',
      'crackeiro',
      'noiado',
      'noia',
      'zika',
      'chato',
      'chata',
      'insuportavel',
      'irritante',
      'tosco',
      'tosca',
      'ridiculo',
      'ridicula',
      'palhaço',
      'palhaca',
      'bobo',
      'boba',
      'burro',
      'burra',
      'analfabeto',
      'analfabeta',
      'ignorante',
      'desinformado',
      'desinformada',
      'fake',
      'mentiroso',
      'mentirosa',
      'falso',
      'falsa',
      'traidor',
      'traidora',
      'infiel',
      'golpista',
      'pilantra',
      'malandro',
      'malandra',
      'mau carater',
      'sem vergonha',
      'safadeza',
      'putaria',
      'sacanagem',
      'obsceno',
      'obscena',
      'pornografia',
      'porno',
      'xxx',
      'sexo',
      'sexual',
      'sensual',
      'erotico',
      'erotica',
      'pervertido',
      'pervertida',
      'tarado',
      'tarada',
      'molestador',
      'molestadora',
      'abusador',
      'abusadora',
      'estuprador',
      'estupradora',
      'violentador',
      'violentadora',
      'agressor',
      'agressora',
      'violento',
      'violenta',
      'perigoso',
      'perigosa',
      'ameaçador',
      'ameaçadora',
      'intimidador',
      'intimidadora',
      'assediador',
      'assediadora',
      'perseguidor',
      'perseguidora',
      'stalker',
      'troll',
      'hater',
      'toxic',
      'toxico',
      'toxica',
      'veneno',
      'demonio',
      'satanas',
      'capeta',
      'diabo',
      'inferno',
      'morte',
      'morto',
      'morta',
      'assombração',
      'primitivo',
      'primitiva',
      'sadico',
      'sadica',
      'masoquista',
      'psicopata',
      'sociopata',
      'demente',
      'perturbado',
      'perturbada',
      'transtornado',
      'transtornada',
      'desequilibrado',
      'desequilibrada',
      'problematico',
      'problematica',
      'imoral',
      'antiético',
      'antietica',
      'corrupto',
      'corrupta',
      'ladrao',
      'ladra',
      'criminoso',
      'criminosa',
      'marginal',
      'delinquente',
      'fora da lei',
      'ilegal',
      'irregular',
      'clandestino',
      'clandestina',
    ]);

    return profanityInstance;
  }, []);

  const checkContent = (
    text: string
  ): { isClean: boolean; message: string } => {
    const normalizedText = text.toLowerCase();
    const isClean =
      !filter.isProfane(normalizedText) && !profanity.exists(normalizedText);

    return {
      isClean,
      message: isClean
        ? 'OK'
        : 'Por favor, escolha um nome apropriado sem palavras inadequadas.',
    };
  };

  return { checkContent };
}
